### ISSUE TITLE
add Mini-Circuits footprints without GND-zone/vias

### ISSUE THREAD

**Issue by aewallin** [KiCad/kicad-footprints#1308]
As discussed in #1133 it was agreed to add "plain" versions of the Mini-Circuits footprints that do not contain GND-zones or GND-vias.

Here is an attempt to list the footprints that are merged, but do not have corresponding "plain" (non GND-zone, non GND-via) footprint in the library.

- [x] BK377 PL-005 #1126 UPDATE: plain footprint PR is #1314
- [x] GP731 PL-176 #1136, plain footprint PR is #1315
- [x] GP1212 PL-176 #1258 (same as GP731 but different height), plain PR is in #1315 
- [x] HF1139 PL-230 #1134, plain footprint PR is #1317
- [x] MMM168 PL-225 #1150, plain footprint PR is #1318
- [x] QQQ130 PL-236 #1135, plain footprint PR is #1323
- [x] TT1224 PL-258 #1128, plain footprint PR is #1324
- [x] YY161 PL-049 #1137, plain footprint PR is #1327
- [x] CK605 PL-012 in #1151, plain footprint PR is #1328
- [x] TTT167 PL-079 in #1133, plain footprint PR is #1329
- [x] HZ1198 PL-247 in #1132, plain footprint PR is #1330

Creating these footprints is straightforward: copy the existing footprint, re-name without "LandPattern" and code, then remove all THT/SMD pads that are GND-zone, i.e. not part of the package pads proper.

**Comment by herostrat** [comment]
Just to understand, do you plan to do the work yourself or is this a "need help" type of issue?

**Comment by aewallin** [comment]
These are not at the top of my to-do list - I may tick them off slowly one by one but don't hold your breath ;)
Please do feel free to work on this!

**Comment by aewallin** [comment]
I think these suggested new "plain" footprints create a bit of an issue with the footprint-filters in the merged symbols.
The plan above is to have two symbols
- mini-circuits_<Case>_LandPattern<PL-Code> with gnd-zones/vias
- mini-circuits_<Case>  the "plain" footprint, no gnd-zones/vias

But in work that is now merged the fp-filter is set to "mini-circuits*<PL-Code>*", so it will *not* match the plain footprint!?

**Comment by poeschlr** [comment]
the footprint filter for the symbol might best mention the case code.
The default footprint should of course use the full footprint name including the land pattern.

**Comment by aewallin** [comment]
these now merged. closing this.
